version: "3.8"

services:
  retail-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: shubhaguha/retail_base
  retail-web:
    build: .
    image: shubhaguha/retail
    ports:
    - "80:80"
    networks:
      - retail-network
    depends_on:
      - retail-memcached
      - retail-base
    environment:
      - MEMCACHED_SERVER=retail-memcached
  retail-memcached:
    image: memcached
    networks:
      - retail-network

networks:
  retail-network:
