apiVersion: 2019-12-01
name: retailContainerGroup
properties:
  containers:
  - name: retail-web
    properties:
      image: shubhaguha/retail:1.0.1
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
        limits:
          cpu: 2
          memoryInGb: 3
      ports:
      - port: 80
  - name: retail-memcached
    properties:
      image: memcached:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
        limits:
          cpu: 1
          memoryInGb: 3
      ports:
      - port: 11211
  osType: Linux
  ipAddress:
    dnsNameLabel: airlab-retail
    type: Public
    ports:
    - protocol: tcp
      port: 80
type: Microsoft.ContainerInstance/containerGroups